// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/google/wire"
	"github.com/liushihao/gostd/conf"
	"github.com/liushihao/gostd/internal/data/api/student"
	"github.com/liushihao/gostd/internal/data/api/student/class"
	"github.com/liushihao/gostd/internal/data/api/student/grades"
	"github.com/liushihao/gostd/internal/data/api/student/user-info"
	"github.com/liushihao/gostd/internal/data/api/teacher"
	"github.com/liushihao/gostd/internal/data/api/teacher/info"
	"github.com/liushihao/gostd/internal/data/conn"
	"github.com/liushihao/gostd/internal/data/dao/studentdao"
	"github.com/liushihao/gostd/internal/data/dao/teacherdao"
	"github.com/liushihao/gostd/logic"
	"github.com/liushihao/gostd/logic/httpserver"
	"github.com/liushihao/gostd/logic/myrpc"
)

// Injectors from wire.go:

func InitApp(cfg *conf.Cfg) (*logic.App, error) {
	studentDB, err := studentdao.NewStudentDB(cfg)
	if err != nil {
		return nil, err
	}
	userInfoRepo := studentdao.NewUserInfoRepo(studentDB)
	classRepo := studentdao.NewClassRepo(studentDB)
	dao := studentdao.NewDao(cfg, studentDB, userInfoRepo, classRepo)
	cli := grades.NewCli(dao)
	userinfoCli := userinfo.NewCli(dao)
	classCli := class.NewCli(dao)
	api := student.NewAPI(cli, userinfoCli, classCli)
	teacherDB, err := teacherdao.NewTeacherDB(cfg)
	if err != nil {
		return nil, err
	}
	infoRepo := teacherdao.NewInfoRepo(teacherDB)
	teacherdbDao := teacherdao.NewDao(cfg, teacherDB, infoRepo)
	infoCli := info.NewCli(teacherdbDao)
	teacherAPI := teacher.NewApi(infoCli)
	client, err := conn.NewRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	server := httpserver.NewServer(cfg, api, teacherAPI, client)
	myrpcServer := myrpc.NewServer(cfg)
	app := logic.NewApp(cfg, server, api, teacherAPI, myrpcServer)
	return app, nil
}

// wire.go:

var studentProviders = wire.NewSet(student.NewAPI, studentdao.NewDao, studentdao.NewStudentDB, studentdao.NewUserInfoRepo, studentdao.NewClassRepo, grades.NewCli, class.NewCli, userinfo.NewCli)

var teacherProviders = wire.NewSet(teacher.NewApi, teacherdao.NewDao, teacherdao.NewTeacherDB, teacherdao.NewInfoRepo, info.NewCli)
