// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"gitea.com/liushihao/gostd/internal/data/api/student"
	"gitea.com/liushihao/gostd/internal/data/api/student/class"
	"gitea.com/liushihao/gostd/internal/data/api/student/grades"
	"gitea.com/liushihao/gostd/internal/data/api/student/user-info"
	"gitea.com/liushihao/gostd/internal/data/api/teacher"
	"gitea.com/liushihao/gostd/internal/data/api/teacher/info"
	"gitea.com/liushihao/gostd/internal/data/conn"
	"gitea.com/liushihao/gostd/internal/data/database/studentdb"
	"gitea.com/liushihao/gostd/internal/data/database/teacherdb"
	"gitea.com/liushihao/gostd/logic"
	"gitea.com/liushihao/gostd/logic/conf"
	"gitea.com/liushihao/gostd/logic/httpserver"
	"gitea.com/liushihao/gostd/logic/myrpc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(cfg *conf.Cfg) (*logic.App, error) {
	studentDB, err := studentdb.NewStudentDB(cfg)
	if err != nil {
		return nil, err
	}
	userInfoRepo := studentdb.NewUserInfoRepo(studentDB)
	classRepo := studentdb.NewClassRepo(studentDB)
	dao := studentdb.NewDao(cfg, studentDB, userInfoRepo, classRepo)
	cli := grades.NewCli(dao)
	userinfoCli := userinfo.NewCli(dao)
	classCli := class.NewCli(dao)
	api := student.NewAPI(cli, userinfoCli, classCli)
	teacherDB, err := teacherdb.NewTeacherDB(cfg)
	if err != nil {
		return nil, err
	}
	infoRepo := teacherdb.NewInfoRepo(teacherDB)
	teacherdbDao := teacherdb.NewDao(cfg, teacherDB, infoRepo)
	infoCli := info.NewCli(teacherdbDao)
	teacherAPI := teacher.NewApi(infoCli)
	client, err := conn.NewRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	server := httpserver.NewServer(cfg, api, teacherAPI, client)
	myrpcServer := myrpc.NewServer(cfg)
	app := logic.NewApp(cfg, server, api, teacherAPI, myrpcServer)
	return app, nil
}

// wire.go:

var studentProviders = wire.NewSet(student.NewAPI, studentdb.NewDao, studentdb.NewStudentDB, studentdb.NewUserInfoRepo, studentdb.NewClassRepo, grades.NewCli, class.NewCli, userinfo.NewCli)

var teacherProviders = wire.NewSet(teacher.NewApi, teacherdb.NewDao, teacherdb.NewTeacherDB, teacherdb.NewInfoRepo, info.NewCli)
